# Generated by Django 4.2.4 on 2023-08-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iha.basemodel')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('iha.basemodel',),
        ),
        migrations.CreateModel(
            name='Iha',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iha.basemodel')),
                ('brand', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_rented', models.BooleanField(default=False)),
                ('iha_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iha.category')),
            ],
            bases=('iha.basemodel',),
        ),
        migrations.CreateModel(
            name='IhaModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iha.basemodel')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('iha.basemodel',),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iha.basemodel')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('rented_iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iha.iha')),
                ('rented_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('iha.basemodel',),
        ),
        migrations.AddField(
            model_name='iha',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iha.ihamodel'),
        ),
    ]
